basic1:
	uvicorn $@:app --host 0.0.0.0 --port 3000 --reload
basic2:
	uvicorn $@:app --host 0.0.0.0 --port 3000 --reload
app1:
	uvicorn $@:app --host 0.0.0.0 --port 3000 --reload
app2:
	uvicorn $@:app --host 0.0.0.0 --port 3000 --reload
app3:
	uvicorn $@:app --host 0.0.0.0 --port 3000 --reload
app4:
	uvicorn $@:app --host 0.0.0.0 --port 3000 --reload