INSERT INTO hr.stdtbl values('김범수','경남');
INSERT INTO hr.stdtbl VALUES ('성시경','서울');
INSERT INTO hr.stdtbl VALUES ('조용필','경기');
INSERT INTO hr.stdtbl VALUES ('은지원','경북');
INSERT INTO hr.stdtbl VALUES ('바비킴','서울');
INSERT INTO hr.clubtbl VALUES ('수영','101호');
INSERT INTO hr.clubtbl VALUES ('바둑','102호');
INSERT INTO hr.clubtbl VALUES ('축구','103호');
INSERT INTO hr.clubtbl VALUES ('봉사','104호');
INSERT INTO hr.stdclubtbl VALUES (stdclubSEQ.NEXTVAL, '김범수','바둑');
INSERT INTO hr.stdclubtbl VALUES (stdclubSEQ.NEXTVAL, '김범수','축구');
INSERT INTO hr.stdclubtbl VALUES (stdclubSEQ.NEXTVAL, '조용필','축구');
INSERT INTO hr.stdclubtbl VALUES (stdclubSEQ.NEXTVAL, '은지원','축구');
INSERT INTO hr.stdclubtbl VALUES (stdclubSEQ.NEXTVAL, '은지원','봉사');
INSERT INTO hr.stdclubtbl VALUES (stdclubSEQ.NEXTVAL, '바비킴','봉사');