 CREATE TABLE "SHOP"."MEMBERTBL" 
   (	"MEMBERID" CHAR(8) NOT NULL ENABLE, 
	"MEMBERNAME" NCHAR(5) NOT NULL ENABLE, 
	"MEMBERADDRESS" NVARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

INSERT INTO "SHOP"."MEMBERTBL" (MEMBERID, MEMBERNAME, MEMBERADDRESS) VALUES ('Dang', N'당탕이', N'경기 부천시 중동');
INSERT INTO "SHOP"."MEMBERTBL" (MEMBERID, MEMBERNAME, MEMBERADDRESS) VALUES ('Jee', N'지운이', N'서울 은평구 중산동');
INSERT INTO "SHOP"."MEMBERTBL" (MEMBERID, MEMBERNAME, MEMBERADDRESS) VALUES ('Han', N'한지연', N'인천 남구 주안동');
INSERT INTO "SHOP"."MEMBERTBL" (MEMBERID, MEMBERNAME, MEMBERADDRESS) VALUES ('Sang', N'상길이', N'경기 성남시 분당구');
