-- USER SQL
CREATE USER "SHOP" IDENTIFIED BY "1234"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "SHOP" QUOTA 10M ON "USERS";

-- ROLES
GRANT "CONNECT" TO "SHOP" ;
GRANT "RESOURCE" TO "SHOP" ;

-- SYSTEM PRIVILEGES