CREATE TABLE "SHOP"."PRODUCTTBL" 
   (	"PRODUCTNAME" NCHAR(4) NOT NULL ENABLE, 
	"COST" NUMBER(7,0) NOT NULL ENABLE, 
	"MAKEDATE" DATE, 
	"COMPANY" NCHAR(5), 
	"AMOUNT" NUMBER(3,0) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

INSERT INTO "SHOP"."PRODUCTTBL" (PRODUCTNAME, COST, MAKEDATE, COMPANY, AMOUNT) VALUES (N'컴퓨터', '10', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), N'삼성', '17');
INSERT INTO "SHOP"."PRODUCTTBL" (PRODUCTNAME, COST, MAKEDATE, COMPANY, AMOUNT) VALUES (N'세탁기', '20', TO_DATE('2018-09-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), N'LG', '3');
INSERT INTO "SHOP"."PRODUCTTBL" (PRODUCTNAME, COST, MAKEDATE, COMPANY, AMOUNT) VALUES (N'냉장고', '5', TO_DATE('2019-02-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), N'대우', '22');
