# Base Images
FROM ubuntu:latest

#RUN Command
RUN echo Hello~ Its Shell Type command.
RUN ["echo" ,"Hello~ It's Exec Type Command."]
RUN ["/bin/bash", "-c", "echo 'Hello~ Its /bin/bash execution in shell type Command.'"]

